### ISSUE TITLE
Columns for checking duplicated entries

### ISSUE THREAD

**Issue by MikeLydeamore** [PascalCrepey/HospitalNetwork#17]
In the function `adjust_overlapping_stays`, the call for `unique(base)` takes over half of the function call time if there is a lot of auxiliary data. Is the intention to check for duplicates using the aux data as well? If not, adding a `by=key(base)` cuts the run time significantly:

```> microbenchmark({unique(vaed.base)}, {unique(vaed.base, by=key(vaed.base))}, times = 10)
Unit: seconds
                             expr     min      lq       mean     median   uq       max         neval
                 {     unique(base) } 30.65674 30.85987 31.83005 31.49651 32.37094 33.96304    10
 {     unique(base, by = key(base)) } 10.43815 10.70215 12.75402 13.49867 14.22774 15.69120    10
```

**Comment by tjibbed** [comment]
I hadn't given the auxiliary data much thought here... I guess that for the moment, we could use `unique(base, by = key(base))`, with the prerequisite that all four primary variables are set as key (right?). 

If I understand it correctly, this would select the unique records irrespective of the auxiliary data, selecting de facto at random one of the records to be kept. We might have to think about selecting based on aux data quality (eg. the least NA values in aux data), but for now `unique(base, by = key(base))` will probably suffice.

**Comment by tjibbed** [comment]
Since the rest of the adjust_overlapping_stays function does not take the aux data into account, what admission is used as first and second if only aux data differs is completely arbitrary at the moment. It therefore doesn't matter which of the records we keep. 

Until we think of a way to chose which aux data to keep, the faster methods is preferable. I changed it accordingly. 

To put it all in perspective: 

In one of my "real" databases, I had 602 duplicates out of 9 million records. These duplicates did all differ in their aux data. However, I have no idea what the "correct" records would have to be, I'd have to go through them by hand. Still, these are records of the same patient being admitted to the same hospital for the same time period. For the reconstruction of the network it doesn't matter. Only if we need or want to use some aux variable, there would be a tiny difference (e.g. admissions for certain diagnoses in certain hospitals)
