### ISSUE TITLE
Hospitals with no transfers get silently dropped

### ISSUE THREAD

**Issue by MikeLydeamore** [PascalCrepey/HospitalNetwork#23]
Not sure if this qualifies as a bug or not, but if there are hospitals present in the database that have admissions but no transfers, they are silently dropped from the transfer matrix. I'd expect a row (and column) of zeroes by default so that the same nodes are present in all elements of the hospinet object.

**Comment by PascalCrepey** [comment]
Thanks a lot Mike for spotting this, to me it sounds like a non-desirable feature, so let's call it a bug ;-). I think it may raises several issues regarding comparability of networks. Thanks to the new interface (and the package itself), it becomes much easier to build several kind of network from the same dataset, and I suspect that having to deal with different sizes of matrices will not help things... At one point in the code we ensure that the matrix is square, I suspect that's where some hospitals are dropped... 
Feel free to do a PR if you have time to fix this, as long as you add a test as well ;-)

**Comment by PascalCrepey** [comment]
After much delay, primarily due to what you can guess... I finally came back to investigate this issue. 
It may not be a bug after all. You need to activate the option `noloops = FALSE` (which is true by default), and you'll need to have patients admitted several times in the same hospital during the window, but you can get something like below:
![Rplot02](https://github.com/user-attachments/assets/9624306f-e5c4-417b-8cf7-39036b343a2b)

I admit that hospitals that only admit patients who have not been to another place in the network (even the current hospital itself) will be dropped simply because they are disconnected. This may become frequent in dynamic networks (like temporal networks) with relatively short time windows. 
A `keep_nodes` option may address this. I'll add this as a feature request for future development.
