### ISSUE TITLE
Features you want to see in the package

### ISSUE THREAD

**Issue by PascalCrepey** [PascalCrepey/HospitalNetwork#6]
Dear all, 
obviously we do not want the package to do everything, but being able to do few relatively simple things would be nice. So I think we need to define a feature set. For the moment, what we've implemented can be split into 4 parts : 
1. Validate and fix data
    * check basic data structure format
    * check and fix dates format
    * check and fix data consistency regarding overlapping stays
1. Perform basic analysis and visualization
    * matrix visualization
    * degree histograms
    * cluster identification
1. Interface with other tools
    * matrix format
    * edgelist format
    * igraph format
1. Simulate real data
    * generate fake patient stays
    * generate fake patient stays with hospital clusters

Now, what else do you want to see in the package ? 
(I do have some ideas but I'll share them in comments... ;-)

**Comment by tjibbed** [comment]
Hi Pascal,

Shouldn't generating the edgelist and/or matrix from the raw database be part of the basic analyses? A rather important functionality of the script, I would say :)

I would suggest some functionality of introducing errors into the simulated data, in particular to test if each step of the data management side of the script identifies and handles the errors correctly. I would suggest the following errors:
- Incorrect date format (e.g. some records are dmy, while others are mdy)
- Overlapping admissions (simple, duplicate a multi-day stay and shift it one day, or introduce a one-day stay on day two of stay >3 days.
- Duplicate records
- Missing values <NA>, or spaces introduced.

**Comment by ClementMassonnaud** [comment]
Hi,
I started writing some code to generate errors in a fake dataset as part of
writing tests to check that the Data management functions work correctly.

For now I generate errors sporadically within the tests but I can easily
isolate the code to make it a separate function. Which would be more
appropriate.

Doing that I also got some errors running the adujst_overlap() function. I
must look into it a bit more.

Best,
Clément

Le ven. 16 août 2019 à 21:24, Tjibbe Donker <notifications@github.com> a
écrit :

**Comment by tjibbed** [comment]
Brilliant, thanks Clément.

I fixed the adjust_overlapping_stays() function, it couldn't handle the
column naming I worked through in the other functions. It didn't pop up on
my radar because the data I was working on didn't have any overlapping
admissions.

Should be fine now, can you double-check?

Cheers, Tjibbe



Op vr 16 aug. 2019 om 17:12 schreef Clement Massonnaud <
notifications@github.com>:

**Comment by ClementMassonnaud** [comment]
Hi,
Great, thank you.
I'll do that ASAP
Best,
Clément

Le lun. 19 août 2019 à 16:31, Tjibbe Donker <notifications@github.com> a
écrit :

**Comment by tjibbed** [comment]
Reading through the minutes of the NeWIS meeting, I noticed we've forgotten about the general summary statistics. We discussed that for each database / country we should extract summary stats such as number of patients, number of hospitals, mean length of stay, etc.

I'll start writing a function to extract these.

**Comment by tjibbed** [comment]
Going through the workflow of the package, isn't it an idea to include the summary statistics of the entire database into the HospiNet class? We can call the functions extracting these stats from the database within the hospinet_from_patient_database() function.

If the HospiNet is not constructed from the patient database directly, but for instance using a pre-constructed edgelist, it just remains empty (NULL). However, if it *was* constructed using the patient database, it would give us the opportunity to easily export the data as one file. 

I think this would greatly improve the collection of data back from all participants.

**Comment by ClementMassonnaud** [comment]
Hi,

I committed modifications to the creation of the fake patient database. I
added the option to introduce errors in the database (wrong date format,
missing values and overlapping stays)
In the meantime, I created some tests to check that the functions in
DataManagement.R work correctly. It seems to be ok, all the errors are
handled as expected. I got no errors for overlapping stays, however I
introduced rather simple overlapping errors. I can't be sure that the
function will work properly in the case of more complicated and intricate
overlaps.
Also I could only test the checkBase() function on a small database. I
don't know what time it would take on a database of several millions
lines... My computer is not powerful enough to generate such a big database
with the create_fakeDB() function... Maybe one of you guys can try to have
an idea. In particular I'm worried about the behavior of the
adjust_overlap() function on a big database due to the "while()" within.

Best,
Clément
